words = [
    "apple", "banana", "orange", "grape", "mango", "peach", "pear", "cherry", "melon", "kiwi",
    "papaya", "lemon", "lime", "coconut", "plum", "apricot", "fig", "guava", "berry", "avocado",
    "car", "train", "bus", "bicycle", "motorcycle", "airplane", "helicopter", "boat", "ship", "submarine",
    "rocket", "tractor", "ambulance", "police", "school", "college", "teacher", "student", "library", "hospital",
    "doctor", "nurse", "engineer", "scientist", "lawyer", "farmer", "pilot", "driver", "artist", "musician",
    "computer", "keyboard", "monitor", "printer", "mouse", "speaker", "internet", "website", "browser", "python",
    "java", "coding", "program", "software", "hardware", "database", "network", "server", "router", "firewall",
    "window", "curtain", "mirror", "table", "chair", "sofa", "bedroom", "kitchen", "garden", "balcony",
    "television", "remote", "refrigerator", "microwave", "washing", "blanket", "pillow", "cupboard", "bottle", "plate",
    "spoon", "fork", "knife", "glass", "coffee", "tea", "juice", "water", "bread", "butter",
    "cheese", "pizza", "burger", "sandwich", "noodles", "pasta", "chocolate", "biscuit", "cookie", "icecream",
    "elephant", "tiger", "lion", "giraffe", "zebra", "monkey", "rabbit", "kangaroo", "panda", "penguin",
    "dolphin", "whale", "octopus", "shark", "crocodile", "alligator", "parrot", "peacock", "sparrow", "eagle",
    "butterfly", "dragonfly", "mosquito", "spider", "antelope", "hamster", "squirrel", "camel", "donkey", "buffalo",
    "planet", "galaxy", "asteroid", "comet", "satellite", "universe", "gravity", "volcano", "desert", "mountain",
    "forest", "river", "ocean", "island", "valley", "waterfall", "rainbow", "thunder", "lightning", "hurricane",
    "summer", "winter", "spring", "autumn", "morning", "evening", "midnight", "holiday", "festival", "birthday",
    "cricket", "football", "basketball", "volleyball", "badminton", "tennis", "hockey", "swimming", "running", "cycling",
    "victory", "defeat", "champion", "stadium", "referee", "captain", "medal", "trophy", "practice", "exercise",
    "friend", "family", "brother", "sister", "mother", "father", "uncle", "aunt", "cousin", "neighbor",
    "happiness", "kindness", "honesty", "freedom", "success", "failure", "adventure", "mystery", "journey", "treasure",
    "diamond", "crystal", "emerald", "golden", "silver", "bronze", "ancient", "future", "history", "culture",
    "library", "notebook", "backpack", "calendar", "painting", "photograph", "umbrella", "airconditioner", "headphones", "microphone",
    "calculator", "flashlight", "backyard", "playground", "restaurant", "supermarket", "shopping", "vacation", "adoption", "celebration",
    "admission", "knowledge", "education", "creativity", "imagination", "motivation", "communication", "friendship", "leadership", "innovation"
]